# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpileDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpileDemo
  pod 'SDWebImage', '~> 4.0.0'
  pod 'JPFPSStatus', '~> 0.1'
  target 'SimpileDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpileDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
